[[CoverM]]
arch = "aarch64"
git-tree-sha1 = "9a3ee6d066127dd520ecd0ba2c6ac81160023ca6"
os = "macos"

    [[CoverM.download]]
    sha256 = "3452439382dc4f72bb1ed7136e03cebdf34cb36fee74a0e060966c9aa218584d"
    url = "https://github.com/JuliaBinaryWrappers/CoverM_jll.jl/releases/download/CoverM-v0.7.0+0/CoverM.v0.7.0.aarch64-apple-darwin.tar.gz"
[[CoverM]]
arch = "x86_64"
git-tree-sha1 = "5e030f134da592c7ff7024fce048e556b52f09a4"
os = "macos"

    [[CoverM.download]]
    sha256 = "bd3934b15406a4db21a929090f0e6b83dfffcebc71adb1d447b22e98a7d532a2"
    url = "https://github.com/JuliaBinaryWrappers/CoverM_jll.jl/releases/download/CoverM-v0.7.0+0/CoverM.v0.7.0.x86_64-apple-darwin.tar.gz"
[[CoverM]]
arch = "x86_64"
git-tree-sha1 = "d00fb0b4fa20c983eb6af3b8eec4519168c110ab"
libc = "glibc"
os = "linux"

    [[CoverM.download]]
    sha256 = "fa7b7d1455068f2331a911ba16bc5a9612b9f95295389723541a2f3d92e09924"
    url = "https://github.com/JuliaBinaryWrappers/CoverM_jll.jl/releases/download/CoverM-v0.7.0+0/CoverM.v0.7.0.x86_64-linux-gnu.tar.gz"
[[CoverM]]
arch = "x86_64"
git-tree-sha1 = "c17c3945e7b5bd4ad357ad6fcecd702d332869a7"
libc = "musl"
os = "linux"

    [[CoverM.download]]
    sha256 = "33c8d5f78a995f798963fd8427815f6d8c6147009b04cee6e9e7d88865c918ae"
    url = "https://github.com/JuliaBinaryWrappers/CoverM_jll.jl/releases/download/CoverM-v0.7.0+0/CoverM.v0.7.0.x86_64-linux-musl.tar.gz"
